// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: service/proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_service_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_service_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// RPCContent carries a message body: either plain text or a list of
// multimodal content parts (base64 images/audio).
type RPCContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RPCContent_Text
	//	*RPCContent_Parts
	Kind          isRPCContent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCContent) Reset() {
	*x = RPCContent{}
	mi := &file_service_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCContent) ProtoMessage() {}

func (x *RPCContent) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCContent.ProtoReflect.Descriptor instead.
func (*RPCContent) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *RPCContent) GetKind() isRPCContent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RPCContent) GetText() string {
	if x != nil {
		if x, ok := x.Kind.(*RPCContent_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *RPCContent) GetParts() *RPCContentParts {
	if x != nil {
		if x, ok := x.Kind.(*RPCContent_Parts); ok {
			return x.Parts
		}
	}
	return nil
}

type isRPCContent_Kind interface {
	isRPCContent_Kind()
}

type RPCContent_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type RPCContent_Parts struct {
	Parts *RPCContentParts `protobuf:"bytes,2,opt,name=parts,proto3,oneof"`
}

func (*RPCContent_Text) isRPCContent_Kind() {}

func (*RPCContent_Parts) isRPCContent_Kind() {}

type RPCContentParts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parts         []*RPCContentPart      `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCContentParts) Reset() {
	*x = RPCContentParts{}
	mi := &file_service_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCContentParts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCContentParts) ProtoMessage() {}

func (x *RPCContentParts) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCContentParts.ProtoReflect.Descriptor instead.
func (*RPCContentParts) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *RPCContentParts) GetParts() []*RPCContentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type RPCContentPart struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Text             string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	InputAudioData   string                 `protobuf:"bytes,4,opt,name=input_audio_data,json=inputAudioData,proto3" json:"input_audio_data,omitempty"`
	InputAudioFormat string                 `protobuf:"bytes,5,opt,name=input_audio_format,json=inputAudioFormat,proto3" json:"input_audio_format,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RPCContentPart) Reset() {
	*x = RPCContentPart{}
	mi := &file_service_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCContentPart) ProtoMessage() {}

func (x *RPCContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCContentPart.ProtoReflect.Descriptor instead.
func (*RPCContentPart) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *RPCContentPart) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RPCContentPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RPCContentPart) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *RPCContentPart) GetInputAudioData() string {
	if x != nil {
		return x.InputAudioData
	}
	return ""
}

func (x *RPCContentPart) GetInputAudioFormat() string {
	if x != nil {
		return x.InputAudioFormat
	}
	return ""
}

type RPCToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCToolCall) Reset() {
	*x = RPCToolCall{}
	mi := &file_service_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCToolCall) ProtoMessage() {}

func (x *RPCToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCToolCall.ProtoReflect.Descriptor instead.
func (*RPCToolCall) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *RPCToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RPCToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RPCToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RPCToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type RPCMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       *RPCContent            `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolCalls     []*RPCToolCall         `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCMessage) Reset() {
	*x = RPCMessage{}
	mi := &file_service_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCMessage) ProtoMessage() {}

func (x *RPCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCMessage.ProtoReflect.Descriptor instead.
func (*RPCMessage) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{6}
}

func (x *RPCMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RPCMessage) GetContent() *RPCContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *RPCMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *RPCMessage) GetToolCalls() []*RPCToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type ChatRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*RPCMessage          `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// system_prompt, when non-empty, overrides the agent prompt entirely
	// (used by non-agent callers such as the commit command).
	SystemPrompt    string          `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Agent           string          `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	Model           string          `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Provider        string          `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Tools           map[string]bool `protobuf:"bytes,6,rep,name=tools,proto3" json:"tools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Backend         string          `protobuf:"bytes,7,opt,name=backend,proto3" json:"backend,omitempty"`
	AgentFiles      bool            `protobuf:"varint,8,opt,name=agent_files,json=agentFiles,proto3" json:"agent_files,omitempty"`
	Confirm         bool            `protobuf:"varint,9,opt,name=confirm,proto3" json:"confirm,omitempty"`
	AllowedCommands []string        `protobuf:"bytes,10,rep,name=allowed_commands,json=allowedCommands,proto3" json:"allowed_commands,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_service_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *ChatRequest) GetMessages() []*RPCMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ChatRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ChatRequest) GetTools() map[string]bool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ChatRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ChatRequest) GetAgentFiles() bool {
	if x != nil {
		return x.AgentFiles
	}
	return false
}

func (x *ChatRequest) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

func (x *ChatRequest) GetAllowedCommands() []string {
	if x != nil {
		return x.AllowedCommands
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*RPCMessage          `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_service_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{8}
}

func (x *ChatResponse) GetMessages() []*RPCMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_service_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{9}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_service_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_service_proto_rawDescGZIP(), []int{10}
}

var File_service_proto_service_proto protoreflect.FileDescriptor

const file_service_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x1bservice/proto/service.proto\x12\x10aishield.service\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"e\n" +
	"\n" +
	"RPCContent\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x129\n" +
	"\x05parts\x18\x02 \x01(\v2!.aishield.service.RPCContentPartsH\x00R\x05partsB\x06\n" +
	"\x04kind\"I\n" +
	"\x0fRPCContentParts\x126\n" +
	"\x05parts\x18\x01 \x03(\v2 .aishield.service.RPCContentPartR\x05parts\"\xad\x01\n" +
	"\x0eRPCContentPart\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12(\n" +
	"\x10input_audio_data\x18\x04 \x01(\tR\x0einputAudioData\x12,\n" +
	"\x12input_audio_format\x18\x05 \x01(\tR\x10inputAudioFormat\"c\n" +
	"\vRPCToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x04 \x01(\tR\targuments\"\xb8\x01\n" +
	"\n" +
	"RPCMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x126\n" +
	"\acontent\x18\x02 \x01(\v2\x1c.aishield.service.RPCContentR\acontent\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x12<\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\x1d.aishield.service.RPCToolCallR\ttoolCalls\"\xae\x03\n" +
	"\vChatRequest\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.aishield.service.RPCMessageR\bmessages\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x14\n" +
	"\x05agent\x18\x03 \x01(\tR\x05agent\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12>\n" +
	"\x05tools\x18\x06 \x03(\v2(.aishield.service.ChatRequest.ToolsEntryR\x05tools\x12\x18\n" +
	"\abackend\x18\a \x01(\tR\abackend\x12\x1f\n" +
	"\vagent_files\x18\b \x01(\bR\n" +
	"agentFiles\x12\x18\n" +
	"\aconfirm\x18\t \x01(\bR\aconfirm\x12)\n" +
	"\x10allowed_commands\x18\n" +
	" \x03(\tR\x0fallowedCommands\x1a8\n" +
	"\n" +
	"ToolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"^\n" +
	"\fChatResponse\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.aishield.service.RPCMessageR\bmessages\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse2\xe0\x01\n" +
	"\tAIService\x12E\n" +
	"\x04Ping\x12\x1d.aishield.service.PingRequest\x1a\x1e.aishield.service.PingResponse\x12E\n" +
	"\x04Chat\x12\x1d.aishield.service.ChatRequest\x1a\x1e.aishield.service.ChatResponse\x12E\n" +
	"\x04Stop\x12\x1d.aishield.service.StopRequest\x1a\x1e.aishield.service.StopResponseB\x18Z\x16ai-shell/service/protob\x06proto3"

var (
	file_service_proto_service_proto_rawDescOnce sync.Once
	file_service_proto_service_proto_rawDescData []byte
)

func file_service_proto_service_proto_rawDescGZIP() []byte {
	file_service_proto_service_proto_rawDescOnce.Do(func() {
		file_service_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_service_proto_rawDesc), len(file_service_proto_service_proto_rawDesc)))
	})
	return file_service_proto_service_proto_rawDescData
}

var file_service_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_service_proto_service_proto_goTypes = []any{
	(*PingRequest)(nil),     // 0: aishield.service.PingRequest
	(*PingResponse)(nil),    // 1: aishield.service.PingResponse
	(*RPCContent)(nil),      // 2: aishield.service.RPCContent
	(*RPCContentParts)(nil), // 3: aishield.service.RPCContentParts
	(*RPCContentPart)(nil),  // 4: aishield.service.RPCContentPart
	(*RPCToolCall)(nil),     // 5: aishield.service.RPCToolCall
	(*RPCMessage)(nil),      // 6: aishield.service.RPCMessage
	(*ChatRequest)(nil),     // 7: aishield.service.ChatRequest
	(*ChatResponse)(nil),    // 8: aishield.service.ChatResponse
	(*StopRequest)(nil),     // 9: aishield.service.StopRequest
	(*StopResponse)(nil),    // 10: aishield.service.StopResponse
	nil,                     // 11: aishield.service.ChatRequest.ToolsEntry
}
var file_service_proto_service_proto_depIdxs = []int32{
	3,  // 0: aishield.service.RPCContent.parts:type_name -> aishield.service.RPCContentParts
	4,  // 1: aishield.service.RPCContentParts.parts:type_name -> aishield.service.RPCContentPart
	2,  // 2: aishield.service.RPCMessage.content:type_name -> aishield.service.RPCContent
	5,  // 3: aishield.service.RPCMessage.tool_calls:type_name -> aishield.service.RPCToolCall
	6,  // 4: aishield.service.ChatRequest.messages:type_name -> aishield.service.RPCMessage
	11, // 5: aishield.service.ChatRequest.tools:type_name -> aishield.service.ChatRequest.ToolsEntry
	6,  // 6: aishield.service.ChatResponse.messages:type_name -> aishield.service.RPCMessage
	0,  // 7: aishield.service.AIService.Ping:input_type -> aishield.service.PingRequest
	7,  // 8: aishield.service.AIService.Chat:input_type -> aishield.service.ChatRequest
	9,  // 9: aishield.service.AIService.Stop:input_type -> aishield.service.StopRequest
	1,  // 10: aishield.service.AIService.Ping:output_type -> aishield.service.PingResponse
	8,  // 11: aishield.service.AIService.Chat:output_type -> aishield.service.ChatResponse
	10, // 12: aishield.service.AIService.Stop:output_type -> aishield.service.StopResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_service_proto_service_proto_init() }
func file_service_proto_service_proto_init() {
	if File_service_proto_service_proto != nil {
		return
	}
	file_service_proto_service_proto_msgTypes[2].OneofWrappers = []any{
		(*RPCContent_Text)(nil),
		(*RPCContent_Parts)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_service_proto_rawDesc), len(file_service_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_service_proto_goTypes,
		DependencyIndexes: file_service_proto_service_proto_depIdxs,
		MessageInfos:      file_service_proto_service_proto_msgTypes,
	}.Build()
	File_service_proto_service_proto = out.File
	file_service_proto_service_proto_goTypes = nil
	file_service_proto_service_proto_depIdxs = nil
}
